### ISSUE TITLE
missing crs/epsg metadata

### ISSUE THREAD

**Issue by contra** [substack/shp2json#19]
It looks like all data is being re-projected to EPSG 4326 but this isn't configurable, specified in the readme, or specified in the metadata of the GeoJSON.

GeoJSON should come with a `crs` field that looks like:

```
crs: {
  type: 'name',
  properties: {
    name: 'EPSG:4326'
  }
}
```

**Comment by contra** [comment]
As a workaround (so the data is usable with any geospatial querying) users can add this data themselves

**Comment by anandthakker** [comment]
I believe the `crs` field either is or is soon to be deprecated.

From https://tools.ietf.org/html/draft-ietf-geojson-04:

> Note: the use of alternative coordinate reference systems was specified in [GJ2008], but has been removed from this version of the specification because the use of different coordinate reference systems -- especially in the manner specified in [GJ2008] -- has proven to have interoperability issues.  In general, GeoJSON processing software is not expected to have access to coordinate reference systems databases or to have network access to coordinate reference system transformation parameters.  However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.

Given that and also the workaround mentioned above, I'd say this is out of scope for this module.

**Comment by contra** [comment]
@anandthakker That seems really strange for them to deprecate it, how else is that data supposed to be conveyed? You can't even load geojson into geospatial databases without that field existing or it doesn't know what coordinate system the data is using.

**Comment by anandthakker** [comment]
> You can't even load geojson into geospatial databases without that field existing or it doesn't know what coordinate system the data is using.

@contra Oh, I didn't include it, but the paragraph above the one I quoted in the spec (section 4) states that "The coordinate reference system for all GeoJSON coordinates is geographic coordinate reference system, using the WGS 84 [WGS84] datum, and with longitude and latitude units of decimal degrees."

**Comment by contra** [comment]
closing since this isnt an issue anymore
