### ISSUE TITLE
Install fails on Node 6.9.1 in OS X El Capitan due to abbrev

### ISSUE THREAD

**Issue by aendrew** [substack/shp2json#21]
I've tried clearing cache and a few other things, but I keep getting this error when I install globally:

```npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "shp2json"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/.staging/abbrev-b15dae74
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-b15dae74' -> '/usr/local/lib/node_modules/shp2json/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-b15dae74' -> '/usr/local/lib/node_modules/shp2json/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aendrew/Sites/learning-d3-v4/npm-debug.log
npm ERR! code 1```

Seems the `abbrev` install is failing. Any ideas?

**Comment by anandthakker** [comment]
Ugh.  I have seen this before when installing some other module, but I can't remember which one.

@aendrew another thing you could try (if you haven't already): explicitly uninstall with `npm uninstall -g shp2json`, and then try again.

**Comment by aendrew** [comment]
@anandthakker I've just uninstalled, cleared cache and reinstalled — no luck, alas. I'm presently upgrading to Node 7.2 to see whether that has any effect. Will update once I've resolved it.

**Comment by aendrew** [comment]
Update: no dice any which way. I think it may be related to: https://github.com/naturalatlas/node-gdal/issues/168

**Comment by aendrew** [comment]
I'm going to close this because I'm pretty sure at this point the issue is with node-gdal and not shp2json.

**Comment by anandthakker** [comment]
Thanks for digging into this (and reporting back)!
